/* Auto-generated by tools/gen_assets.py — do not edit by hand. */
#ifndef GBTD_ASSETS_H
#define GBTD_ASSETS_H

#include "gtypes.h"

/* BG tile bank: tiles 0..127 hold ASCII font glyphs, tiles 128.. hold map
 * tiles (TILE_GROUND, TILE_PATH, TILE_COMP_*). Sprite tiles live in their
 * own VRAM bank starting at sprite tile index 0 (SPR_*). */

#define MAP_TILE_BASE   128
#define TILE_GROUND     (MAP_TILE_BASE + 0)
#define TILE_PATH       (MAP_TILE_BASE + 1)
#define TILE_COMP_TL    (MAP_TILE_BASE + 2)
#define TILE_COMP_TR    (MAP_TILE_BASE + 3)
#define TILE_COMP_BL    (MAP_TILE_BASE + 4)
#define TILE_COMP_BR    (MAP_TILE_BASE + 5)
#define TILE_COMP_TL_D  (MAP_TILE_BASE + 6)
#define TILE_COMP_TR_D  (MAP_TILE_BASE + 7)
#define TILE_COMP_BL_D  (MAP_TILE_BASE + 8)
#define TILE_COMP_BR_D  (MAP_TILE_BASE + 9)
#define TILE_TOWER      (MAP_TILE_BASE + 10)
#define TILE_TOWER_2    (MAP_TILE_BASE + 11)
#define TILE_COMP_TL_C1 (MAP_TILE_BASE + 12)
#define TILE_COMP_TL_C2 (MAP_TILE_BASE + 13)
#define TILE_COMP_TR_C2 (MAP_TILE_BASE + 14)
#define TILE_COMP_TL_C3 (MAP_TILE_BASE + 15)
#define TILE_COMP_TR_C3 (MAP_TILE_BASE + 16)
#define TILE_COMP_BL_C3 (MAP_TILE_BASE + 17)
#define TILE_COMP_BR_C3 (MAP_TILE_BASE + 18)
#define TILE_TOWER_B    (MAP_TILE_BASE + 19)
#define TILE_TOWER_2_B  (MAP_TILE_BASE + 20)
#define TILE_TOWER_3    (MAP_TILE_BASE + 21)
#define TILE_TOWER_3_B  (MAP_TILE_BASE + 22)
#define TILE_TOWER_L1     (MAP_TILE_BASE + 23)
#define TILE_TOWER_L1_B   (MAP_TILE_BASE + 24)
#define TILE_TOWER_2_L1   (MAP_TILE_BASE + 25)
#define TILE_TOWER_2_L1_B (MAP_TILE_BASE + 26)
#define TILE_TOWER_3_L1   (MAP_TILE_BASE + 27)
#define TILE_TOWER_3_L1_B (MAP_TILE_BASE + 28)
#define MAP_TILE_COUNT  29

#define SPR_CURSOR_A    0
#define SPR_CURSOR_B    1
#define SPR_CURSOR_GA   2
#define SPR_CURSOR_GB   3
#define SPR_TOWER       4
#define SPR_BUG_A       5
#define SPR_BUG_B       6
#define SPR_PROJ        7
#define SPR_ROBOT_A     8
#define SPR_ROBOT_B     9
#define SPR_GLYPH_U     10
#define SPR_GLYPH_P     11
#define SPR_GLYPH_G     12
#define SPR_GLYPH_S     13
#define SPR_GLYPH_E     14
#define SPR_GLYPH_L     15
#define SPR_GLYPH_COLON 16
#define SPR_GLYPH_GT    17
#define SPR_GLYPH_DASH  18
#define SPR_GLYPH_0     19
#define SPR_GLYPH_1     20
#define SPR_GLYPH_2     21
#define SPR_GLYPH_3     22
#define SPR_GLYPH_4     23
#define SPR_GLYPH_5     24
#define SPR_GLYPH_6     25
#define SPR_GLYPH_7     26
#define SPR_GLYPH_8     27
#define SPR_GLYPH_9     28
#define SPR_GLYPH_A     29
#define SPR_GLYPH_R     30
#define SPR_GLYPH_M     31
#define SPR_GLYPH_Q     32
#define SPR_GLYPH_I     33
#define SPR_GLYPH_T     34
#define SPR_BUG_FLASH   35
#define SPR_ROBOT_FLASH 36
#define SPR_ARMORED_A     37
#define SPR_ARMORED_B     38
#define SPR_ARMORED_FLASH 39
#define SPR_BUG_STUN      40
#define SPR_ROBOT_STUN    41
#define SPR_ARMORED_STUN  42
#define SPRITE_TILE_COUNT 43

extern const unsigned char font_tiles[];   /* 128 tiles * 16 bytes */
extern const unsigned char map_tile_data[]; /* MAP_TILE_COUNT * 16 bytes */
extern const unsigned char sprite_tile_data[]; /* SPRITE_TILE_COUNT * 16 bytes */

extern const unsigned char title_tilemap[20*18];
extern const unsigned char win_tilemap[20*18];
extern const unsigned char lose_tilemap[20*18];

/* Iter-3 #17: three selectable maps. Map 1 is the canonical replacement
 * for the pre-iter-3-17 `gameplay_tilemap` / `gameplay_classmap` /
 * waypoint set (Map 1 bytes are byte-identical to the legacy data).
 * Plain `const` (NOT `static const`) so external linkage is preserved. */
#include "map.h"   /* waypoint_t */

extern const unsigned char gameplay1_tilemap[20*17];
extern const unsigned char gameplay1_classmap[20*17];
extern const unsigned char gameplay2_tilemap[20*17];
extern const unsigned char gameplay2_classmap[20*17];
extern const unsigned char gameplay3_tilemap[20*17];
extern const unsigned char gameplay3_classmap[20*17];

extern const waypoint_t gameplay1_waypoints[8];
extern const waypoint_t gameplay2_waypoints[10];
extern const waypoint_t gameplay3_waypoints[8];

#endif
